//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Upd8API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwClienteComLocalizacaoCompleta
    {
        public int Id { get; set; }
        public string Nome { get; set; }
        public string CPF { get; set; }
        public Nullable<System.DateTime> DtNascimento { get; set; }
        public Nullable<bool> Sexo { get; set; }
        public string Endereco { get; set; }
        public Nullable<int> EstadoId { get; set; }
        public Nullable<int> MunicipioId { get; set; }
        public string UF { get; set; }
        public string Cidade { get; set; }
    }
}
